### ISSUE TITLE
"java.lang.NoSuchFieldError: type" in EcjConverter

### ISSUE THREAD

**Issue by tnorbye** [rzwitserloot/lombok.ast#2]
When running the EcjTreeConverter I get the following NoSuchFieldError on a bunch of different files. This is using Eclipse 3.7.1, on Mac OSX Snow Leopard.  The Lombok AST library is from head a couple of days ago.

java.lang.NoSuchFieldError: type
     at lombok.ast.ecj.EcjTreeConverter$2.visitCastExpression(EcjTreeConverter.java:831)
     at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:280)
     at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:289)
     at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:230)
     at lombok.ast.ecj.EcjTreeConverter.toTree(EcjTreeConverter.java:223)
     at lombok.ast.ecj.EcjTreeConverter.createVariableDefinition(EcjTreeConverter.java:345)
     at lombok.ast.ecj.EcjTreeConverter.toVariableDefinition(EcjTreeConverter.java:299)
     at lombok.ast.ecj.EcjTreeConverter.fillList(EcjTreeConverter.java:274)
      ... lots of frames ...

     at lombok.ast.ecj.EcjTreeConverter$2.visitCompilationUnitDeclaration(EcjTreeConverter.java:434)
     at lombok.ast.ecj.EcjTreeVisitor.visitEcjNode(EcjTreeVisitor.java:264)
     at lombok.ast.ecj.EcjTreeConverter.visit(EcjTreeConverter.java:289)
  
I get this on this file:
http://codesearch.google.com/#Z1yw3OC_QbA/astrid/rmilk-src/org/weloveastrid/rmilk/api/Invoker.java
(well I'm running it on a snapshot of that project which is older, but I'm hoping the above file will still trigger it, if not I can send it to you directly)

**Comment by rspilker** [comment]
The Lombok issue tracker has moved to github. Issue 312 is now https://github.com/rzwitserloot/lombok/issues/385 and closed already.
